# Generated by Django 3.2.5 on 2021-08-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0002_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='region_name',
        ),
    ]
