# Generated by Django 3.2.5 on 2021-08-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0003_rename_region_region_region_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='geom',
            new_name='mpoly',
        ),
    ]
