# Generated by Django 3.2.5 on 2021-08-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0004_rename_geom_region_mpoly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='mpoly',
            new_name='polygon',
        ),
    ]
