# Generated by Django 3.2.5 on 2021-08-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0007_precipitation1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precipitation1',
            new_name='Precipitation',
        ),
    ]
