# Generated by Django 3.2.5 on 2021-08-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0008_rename_precipitation1_precipitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precipitation',
            name='valeur_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='precipitation',
            name='valeur_min',
            field=models.FloatField(),
        ),
    ]
