# Generated by Django 3.2.5 on 2021-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0009_auto_20210819_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('auteur', models.CharField(max_length=100)),
                ('nombre_de_pages', models.IntegerField()),
                ('date_insertion', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('Format', models.IntegerField(choices=[(1, 'PDF'), (2, 'WORD'), (3, 'CSV')], default=1)),
                ('photo', models.ImageField(upload_to='media')),
                ('fichier', models.FileField(upload_to='media')),
            ],
        ),
    ]
