# Generated by Django 3.2.5 on 2021-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0010_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='titre',
            field=models.CharField(max_length=150),
        ),
    ]
