# Generated by Django 3.2.5 on 2021-08-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0012_action_company_investor_organisation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company',
            new_name='Entreprise',
        ),
        migrations.RenameModel(
            old_name='Investor',
            new_name='Investisseur',
        ),
    ]
