# Generated by Django 3.2.5 on 2021-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0015_auto_20210825_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='nombre_employes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investisseur',
            name='nombre_employes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='nombre_employes',
            field=models.CharField(max_length=100),
        ),
    ]
