# Generated by Django 3.2.5 on 2021-08-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0017_auto_20210827_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investisseur',
            name='action',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='action',
        ),
        migrations.CreateModel(
            name='OrganisationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='climatechange.action')),
                ('organisation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='climatechange.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='InvestisseurAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='climatechange.action')),
                ('investisseur', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='climatechange.investisseur')),
            ],
        ),
    ]
