# Generated by Django 3.2.5 on 2021-08-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0018_auto_20210827_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(1, 'Réduction des émissions'), (2, 'Établissement du prix du carbone'), (3, 'Efficacité énergétique'), (4, 'Investissement'), (5, 'Énergie renouvelable'), (6, 'La consommation de ressources'), (7, 'Assurance des obligations')], default=1),
        ),
    ]
