# Generated by Django 3.2.5 on 2021-09-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0020_action_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='Location',
        ),
    ]
