# Generated by Django 3.2.5 on 2021-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0021_remove_action_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='Location',
            field=models.IntegerField(choices=[(1, 'Maroc'), (2, 'Tunisie'), (3, 'Algérie'), (4, 'Egypte'), (5, 'Espagne')], default=1),
        ),
    ]
