# Generated by Django 3.2.5 on 2021-09-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0022_action_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatechange.region'),
        ),
    ]
