# Generated by Django 3.2.5 on 2021-09-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatechange', '0025_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='precipitation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatechange.station'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climatechange.station'),
        ),
    ]
